# Sentence transformers



In [2]:
!pip install sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 kB 2.9 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

### Generate Embedding

In [3]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
sentences = ["the sentence transformer create embeddings for each sentence", "Sentences are passed as a list of strings"]

embedding = model.encode(sentences)



In [5]:
for sentence, embed in zip(sentences, embedding):
  print("sentence ", sentence)
  print("Embedding ", embed)
  print("\n\n")


sentence  the sentence transformer create embeddings for each sentence
Embedding  [-6.34327903e-02 -1.87817048e-02  3.12387105e-02  8.53592902e-03
  4.17685062e-02  5.97180761e-02 -3.60339228e-03  2.75155231e-02
  9.17139798e-02 -6.51020184e-02  4.76635844e-02  1.52092450e-03
  2.58961041e-02  4.99740206e-02 -1.64022949e-02  8.27808902e-02
 -3.01328432e-02  9.19115841e-02 -8.76922011e-02 -1.13994502e-01
  6.07929053e-03  5.17733470e-02  3.97965461e-02 -6.41652048e-02
  2.72861458e-02  7.30041489e-02 -3.14763002e-02 -2.94154976e-02
  6.07119128e-02 -3.66231124e-03  3.30002117e-03 -8.06924030e-02
 -3.19759473e-02  1.22160494e-01 -1.98643971e-02  1.85805149e-02
  2.45001968e-02  7.93173462e-02 -2.42363401e-02  1.46340346e-02
  3.14277299e-02 -5.72534045e-03  4.91057225e-02  2.19561867e-02
  5.33413403e-02 -2.30435375e-02 -4.12100367e-02  9.15259589e-03
 -1.80257093e-02  1.83984563e-02 -4.22465242e-02 -5.04804440e-02
  8.73716024e-04  8.30834582e-02 -2.96548530e-02  3.99233513e-02
 -5.8556

## Coseing Similarity

In [6]:
emb1 = model.encode("I like apple but I don't eat")
emb2 = model.encode("I love apples")

cos_sim = util.cos_sim(emb1, emb2)
print("cosing similarity:", cos_sim)

cosing similarity: tensor([[0.6448]])


Compute cosine similarity between all pairs

In [7]:
sentences = ["A man is eating food",
             " a man is eating a piece of bread ",
             "The girl is carrying a baby",
             "A woman is playing violin",
             "two men pushed carts through the woods",
             "A man is riding a white horse on an enclosed ground",
             "A monkey is playing drums",
             "someone in a gorilla costume is playing a set of drums"]


In [8]:
# encode all sentences

embeddings = model.encode(sentences)

# Compute the cosine similarity between all pairs
cos_sim = util.cos_sim(embeddings, embeddings)

cos_sim

tensor([[ 1.0000,  0.7379, -0.1136, -0.0741, -0.0294,  0.1664,  0.0453,  0.0501],
        [ 0.7379,  1.0000, -0.0666, -0.0833, -0.0146,  0.1129,  0.0386,  0.0074],
        [-0.1136, -0.0666,  1.0000,  0.0207, -0.0301, -0.0930,  0.0253,  0.0202],
        [-0.0741, -0.0833,  0.0207,  1.0000, -0.1546, -0.0560,  0.1957,  0.2439],
        [-0.0294, -0.0146, -0.0301, -0.1546,  1.0000,  0.0859, -0.0309, -0.0869],
        [ 0.1664,  0.1129, -0.0930, -0.0560,  0.0859,  1.0000,  0.0513,  0.1162],
        [ 0.0453,  0.0386,  0.0253,  0.1957, -0.0309,  0.0513,  1.0000,  0.6376],
        [ 0.0501,  0.0074,  0.0202,  0.2439, -0.0869,  0.1162,  0.6376,  1.0000]])

In [9]:
# Add all pairs to a list with their cosine similarity score

all_sentence_combination = []

for i in range(len(cos_sim)-1):
  for j in range(i+1, len(cos_sim)):
    all_sentence_combination.append((cos_sim[i][j], i, j))

all_sentence_combination

[(tensor(0.7379), 0, 1),
 (tensor(-0.1136), 0, 2),
 (tensor(-0.0741), 0, 3),
 (tensor(-0.0294), 0, 4),
 (tensor(0.1664), 0, 5),
 (tensor(0.0453), 0, 6),
 (tensor(0.0501), 0, 7),
 (tensor(-0.0666), 1, 2),
 (tensor(-0.0833), 1, 3),
 (tensor(-0.0146), 1, 4),
 (tensor(0.1129), 1, 5),
 (tensor(0.0386), 1, 6),
 (tensor(0.0074), 1, 7),
 (tensor(0.0207), 2, 3),
 (tensor(-0.0301), 2, 4),
 (tensor(-0.0930), 2, 5),
 (tensor(0.0253), 2, 6),
 (tensor(0.0202), 2, 7),
 (tensor(-0.1546), 3, 4),
 (tensor(-0.0560), 3, 5),
 (tensor(0.1957), 3, 6),
 (tensor(0.2439), 3, 7),
 (tensor(0.0859), 4, 5),
 (tensor(-0.0309), 4, 6),
 (tensor(-0.0869), 4, 7),
 (tensor(0.0513), 5, 6),
 (tensor(0.1162), 5, 7),
 (tensor(0.6376), 6, 7)]

In [10]:
# Sort list by the highest cosine similarity score

all_sentence_combinations = sorted(all_sentence_combination, key=lambda x: x[0], reverse=True)

print("Top - 5 most similiar pair: ")
for score, i, j in all_sentence_combinations[0:5]:
  print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))

Top - 5 most similiar pair: 
A man is eating food 	  a man is eating a piece of bread  	 0.7379
A monkey is playing drums 	 someone in a gorilla costume is playing a set of drums 	 0.6376
A woman is playing violin 	 someone in a gorilla costume is playing a set of drums 	 0.2439
A woman is playing violin 	 A monkey is playing drums 	 0.1957
A man is eating food 	 A man is riding a white horse on an enclosed ground 	 0.1664


# Semantic search

In [11]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('clips/mfaq')

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.74k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/778 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:363: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/464 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [12]:

question = "<Q>How many models can I host on HuggingFace?"
answer_1 = "<A>All plans come with unlimited private models and datasets."
answer_2 = "<A>AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "<A>Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."

query_embedding = model.encode(question)
corpus_embeddings = model.encode([answer_1, answer_2, answer_3])

print(util.semantic_search(query_embedding, corpus_embeddings))

[[{'corpus_id': 0, 'score': 0.5646328926086426}, {'corpus_id': 2, 'score': 0.5142345428466797}, {'corpus_id': 1, 'score': 0.4730043113231659}]]


In [13]:
from transformers import pipeline

In [14]:
qa_model = pipeline("question-answering")

question = "How many models can I host on HuggingFace?"
context = "All plans come with unlimited private models and datasets."

qa_model(question = question, context = context)

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

{'score': 0.7017179727554321, 'start': 20, 'end': 29, 'answer': 'unlimited'}

In [15]:
print(util.semantic_search(query_embedding, corpus_embeddings))

[[{'corpus_id': 0, 'score': 0.5646328926086426}, {'corpus_id': 2, 'score': 0.5142345428466797}, {'corpus_id': 1, 'score': 0.4730043113231659}]]


# Clustering

In [16]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]
corpus_embeddings = embedder.encode(corpus)

# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [17]:
corpus_embeddings[0]

array([ 3.32415812e-02,  4.40608943e-03, -6.27701962e-03,  4.83787358e-02,
       -1.38702273e-01, -3.36174294e-02,  1.01128317e-01, -5.43849580e-02,
       -4.32477668e-02, -3.99410948e-02,  7.78631913e-03, -1.27488943e-02,
       -6.68302253e-02, -1.73865985e-02,  4.74505872e-02, -5.77242821e-02,
        1.01888381e-01, -9.11651587e-04,  8.22614729e-02, -5.03415577e-02,
        6.77303076e-02,  4.08765152e-02, -3.58018391e-02, -1.00682430e-01,
       -6.69358438e-03, -5.31685986e-02,  1.00335173e-01, -5.46136312e-02,
       -2.28481628e-02,  1.38387065e-02,  7.48658180e-02, -6.17880225e-02,
        6.39215782e-02,  1.62387230e-02, -5.32299690e-02, -3.86083722e-02,
        3.15276198e-02, -8.11530128e-02, -3.31432149e-02, -5.38532506e-04,
       -3.96069884e-03, -1.52734034e-02, -9.86389932e-04,  9.57987979e-02,
       -5.42920232e-02,  1.84572078e-02, -1.07143648e-01,  1.38885034e-02,
        3.94072905e-02, -2.69243419e-02, -9.15988833e-02, -1.14195300e-02,
        3.38137001e-02, -

In [18]:
# source: https://stackoverflow.com/questions/55619176/how-to-cluster-similar-sentences-using-bert

clustering_model = KMeans(n_clusters=4)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[1 1 0 1 1 2 2 0 0 3 3 0 0 0 2]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [19]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{1: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 0: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 2: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 3: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}